# Generated by the fcbnerd release workflow
# (github.com/JamesRyanATX/fcbnerd/blob/main/.github/scripts/render-formula.sh).
# Edit it there, not here: the next release overwrites this file.
class Fcbnerd < Formula
  desc "Bind MIDI foot controller events to shell commands, or stream them as JSON"
  homepage "https://github.com/JamesRyanATX/fcbnerd"
  url "https://github.com/JamesRyanATX/fcbnerd/releases/download/v0.2.1/fcbnerd-0.2.1-macos-universal.tar.gz"
  sha256 "15ecc6c2fe4d349d10a2b0140645aa18af824d9e7745c53d0441cf3eb1d0c918"
  license "MIT"
  head "https://github.com/JamesRyanATX/fcbnerd.git", branch: "main"

  depends_on macos: :ventura

  def install
    if build.head?
      # Homebrew already sandboxes the build; SwiftPM's own sandbox can't nest inside it.
      system "swift", "build", "--disable-sandbox", "--configuration", "release"
      bin.install ".build/release/fcbnerd"
    else
      bin.install "fcbnerd"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fcbnerd --version") unless build.head?
    assert_match "unexpected argument", shell_output("#{bin}/fcbnerd bogus 2>&1", 64)
    assert_match "controller must be 0-127", shell_output("#{bin}/fcbnerd --bind '1:200:1=true' 2>&1", 64)
  end
end
